apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8-dotnet-sandbox
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8-dotnet-sandbox
    spec:
      containers:
        - name: k8-dotnet-sandbox
          imagePullPolicy: Never
          image: k8-dotnet-sandbox
          ports:
            - containerPort: 80
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP